resources:
  containers:
    - container: mlops
      image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - code/

variables:
  - group: kubefow-azdo-sample

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "Model_CI"
    displayName: "Model CI"
    jobs:
      - job: "Model_CI_Pipeline"
        displayName: "Model CI Pipeline"
        container: mlops
        timeoutInMinutes: 0
        steps:
          - template: code-quality-template.yml

  - stage: "Build_and_Push_Images"
    displayName: "Build and Push Images"
    variables:
      Jobs:
        Job:
        steps:
