apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-file
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 300Gi
