apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: custom
spec:
  default:
    predictor:
      custom:
        container:
          image: eugenefedorenko/samplemodel:custom
