apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk-new
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 300Gi
